### ISSUE TITLE
Clarification about incomplete files from previous month

### ISSUE THREAD

**Issue by jarl-tornroos** [flexera-public/cbi-oi-kubecost-exporter#32]
@JesusParada why is it important that all files exist when uploading data from the previous month? Does Flexera delete existing data if there are missing files? https://github.com/flexera-public/cbi-oi-kubecost-exporter/blob/dcf570349798c19296c638f4adfea599868f7154/main.go#L264-L268

**Comment by JesusParada** [comment]
HI Jarl! When the upload of files from the previous month was created, it
was not considered that some clients have the FILE_ROTATION option
activated, which eliminates files created for previous months, so when
enabling the upload of files from the previous month, it will not always be
possible to re-create them with the information obtained from the KUBECOST
API, since some use the free subscription which only stores the last 15
days of cost information. This is why that validation was added.
For example, a customer with the FILE_ROTATION option activated and with
the free version of kubecost API that activates the upload of files from
the previous month on January 3, will only have data from the last 12 days
of December to create new cost files, and since the files from the other
days will no longer exist, a load of bills for those 12 days only will be
created, which will generate inaccurate data.
The current version of the exporter stores the data of the current and
previous month for all clients, but previously it was only done for the
current month, so this validation would only apply to those clients who
have old versions of the exporter and update their version and comply with
the conditions detailed above.
